### ISSUE TITLE
Build errors when installing with Node Versions >= 12.*

### ISSUE THREAD

**Issue by schroffl** [schroffl/node-lzo#14]
Building the package with the new 12.* versions of Node.js results in a build errors.
See [this comment](https://github.com/schroffl/node-lzo/issues/9#issuecomment-487847521) from @Naisunev.

**Comment by schroffl** [comment]
@Naisunev Published in Version [0.4.11](https://www.npmjs.com/package/lzo/v/0.4.11)

**Comment by Naisunev** [comment]
tested and works! thanks!

**Comment by schroffl** [comment]
Great, glad to hear that :)
