### ISSUE TITLE
Buffer question

### ISSUE THREAD

**Issue by afenderson** [schroffl/node-lzo#3]
Apologies in advance as I think this is a question that will just help my understanding rather than an issue (I think). 

I have a createReadStream instantiated from the 'webhdfs' package. I can read in a stream of json coming from this filesystem no problem, via the chunk method, and I can serve up the full contents of that file via express endpoint. All good. The problem is when I have an lzo compressed file on that file system.

I've tried a few different ways and I either segmentation fault or it complains about how the buffer has to be an array, or just shows the buffer output, etc, depending on how I code it.

The most current, which I feel is close to what I'm supposed to be doing, looks like this:
```
var remoteFileStream = hdfs.createReadStream('/user/me/telemetry_hdfs.'+req.params.hdfsfile);

var data = new Buffer();

  remoteFileStream.on('data', function onChunk (chunk) {
    // Concatenate the chunks into the buffer
    data = Buffer.concat([data, chunk]);
    console.log(bufferdata);
 })
```

Then I'd go on to decompress using lzo when the full data has been received. 

The problem is I can't get past this error:
```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:280:9)
    at Function.Buffer.from (buffer.js:106:10)
    at new Buffer (buffer.js:85:17)
    at /home/centos/telemetry/new_hdfstest.js:36:14
    at Layer.handle [as handle_request] (/home/centos/telemetry/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/centos/telemetry/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/centos/telemetry/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/centos/telemetry/node_modules/express/lib/router/layer.js:95:5)
    at /home/centos/telemetry/node_modules/express/lib/router/index.js:281:22
    at param (/home/centos/telemetry/node_modules/express/lib/router/index.js:354:14)
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object
```

If I instantiate the Buffer() with an **empty string** inside, I don't error out, so I know the "new Buffer()" piece might have problems as I am instantiating as a string.. Here is what I'm talking about:

```
  var data = new Buffer('');  /// <<<< ------ HERE
  var rawchunk;

  var chunklength=0;

  remoteFileStream.on('data', function onChunk (chunk) {
    // Do something with the data chunk
    chunklength += chunk.length;
    console.log(chunklength);

    data = Buffer.concat([data, chunk]);
  })
```

But then when I console out what "data" is after the full buffer is finished, it appears I only have 1 of the buffer chunks, though I know it fully completes. Here is what the output looks like:

```
....
18518867
18584403
18649939
18715475
18781011
18846547
18912083
18977619
19043155
19108691
19174227
19239763
19305299
19370835
19436371
19501907
19567443
19632979
19698515
19764051
19829587
19895123
19960659
20026195
20091731
20157267
20222803
20288339
20353875
20419411
20428832
<Buffer 89 4c 5a 4f 00 0d 0a 1a 0a 10 20 20 30 09 40 01 05 03 00 00 0d 00 00 00 00 59 23 90 aa 00 00 00 00 00 1e e1 02 96 00 04 00 00 00 00 65 39 5f fb 32 25 ... >
read is fully complete
```

The code snippet that produced that output, including the on('finish') method was this:
```
  var data = new Buffer('');
  var chunklength=0;

   remoteFileStream.on('data', function onChunk (chunk) {
    // Do something with the data chunk

    chunklength += chunk.length;
    console.log(chunklength);
    data = Buffer.concat([data, chunk]);
   })

  remoteFileStream.on('finish', function onFinish () {
    // Read is done
    console.log(data)
    console.log('read is fully complete')]\
  });
```

I was thinking I would put the lzo.decompress() in that last on('finish') method, but the fact that console.log(data) only produces 1 line makes me think there is something wrong.. I get a Segmentation fault when I try to decompress it! Here is the code where I'm trying to do the actual **lzo.decompress()**:

```
remoteFileStream.on("finish", function onFinish () {
    // Read is done
    console.log('read is fully complete')
    var decompressed = lzo.decompress(data)
  });
```
I've also tried doing a .pipe(lzo.decompress()) at the end of the hdfs.createReadStream(), and that fails in other ways. It would be cool to figure out how to do it like that but I feel like I should at least be able to figure out this buffer approach. I know this is not an "issue" with the LZO package rather more of a clarification of how it can be used with a buffer, and helping me understand the buffer in general, so I appreciate the patience in advance!!

Thanks!
Chris

**Comment by schroffl** [comment]
First of all: `.pipe(lzo.decompress())` doesn't work, because `lzo.decompress` doesn't return a stream. You can take a look at the [Stream API Documentation](https://nodejs.org/api/stream.html) for more information about streams in Node.js. I already thought about implementing a Stream API, now I might finally do it.

Regarding your concern about how there's only one line being logged: Node.js strips buffers if they are too long so that they don't flood your console (I assume). This is indicated by the `...` in the end.

I don't know what exactly causes the SEGFAULT. I'm not very experienced with C++ and I only developed this package because I needed it and didn't find anything else. Maybe chunking your data into smaller pieces helps (?).
I would just try to experiment and find out what causes this problem. And if you know C++, feel free to look at [this file](https://github.com/schroffl/node-lzo/blob/master/lib/lzo.cc). Maybe you can spot anyting wrong with my code.

**Comment by afenderson** [comment]
Thanks for the quick reply sir! I'm going to be lost in the c++ code. Good to know why the pipe() doesn't work, I will stop pursuing that path. ;)

**Comment by afenderson** [comment]
And just to confirm, does the buffer approach with storing into a variable and then decompressing from that on('finish') method sound sound, though, in your opinion? Do you see anything wrong with the way I'm doing it, besides maybe breaking into smaller chunks?

**Comment by afenderson** [comment]
OK, I think I'm getting somewhere.. I have made the following changes:

```
  var data = Buffer.allocUnsafe(10); //NEW UPDATE
  var newdata;
  var chunklength=0;

  remoteFileStream.on('data', function onChunk (chunk) {
    // Do something with the data chunk
    chunklength += chunk.length;
    console.log(chunklength);
    newdata = Buffer.concat([data, chunk]);
  })

  remoteFileStream.on('finish', function onFinish () {
    // Read is done
    //console.log('read is fully complete',newdata.toString())  //NEW UPDATE - I can see a lot of encrypted text, seems like it is the lzo data
    var decompressed = lzo.decompress(newdata); //NEW UPDATE (seems like this is all I would need)
  });
```

But I get this error:

```
/home/centos/telemetry/node_modules/lzo/index.js:60
                        throw new Error('Decompression failed with code: ' + errCodes[result.err]);
                        ^

Error: Decompression failed with code: LZO_E_INPUT_NOT_CONSUMED
    at Object.decompress (/home/centos/telemetry/node_modules/lzo/index.js:60:10)
    at Request.onFinish (/home/centos/telemetry/new_hdfstest.js:42:28)
    at emitNone (events.js:86:13)
    at Request.emit (events.js:188:7)
    at Request.<anonymous> (/home/centos/telemetry/node_modules/webhdfs/lib/webhdfs.js:643:9)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/centos/telemetry/node_modules/request/request.js:1108:14)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
```

Thoughts?

**Comment by afenderson** [comment]
I tried to simply to data+=chunk, and that yields a better result when i console it out upon finish, but when i try to decompress it seg faults.

```
  var data;

  remoteFileStream.on('data', function onChunk (chunk) {
    data+=chunk
  })

  remoteFileStream.on('finish', function onFinish () {
    let decompressed = lzo.decompress(data); //This is where i seg fault
    console.log(decompressed.toString());
  });
```

Does this super simple example I'm doing even make sense?

**Comment by schroffl** [comment]
If you chunk your data, compress these chunks and then concatenate them again to store them, you'll have to keep in mind that you have to do the same thing when decompressing them. Besides that I don't know how big your data can get, but if it's not limited to some very small size, you will eventually have to split it up anyways. Being heavily dependent on what system you intend to run your program on, it's probably still better if you implement it from the very beginning.

As for further help I would like to contact you in some other way than this Issue. It's really getting out of scope of this package and it would be a lot easier to help if I'd know a bit more about what you are doing.
