### ISSUE TITLE
hard crash (segfault) fault when decompressing data

### ISSUE THREAD

**Issue by asmuth** [schroffl/node-lzo#5]
const lzo = require('lzo');
    const str = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    const str_ = lzo.decompress(lzo.compress(str));
    console.log(str_);

Above example reliably triggers a crash:

    → node boom.js     
    zsh: segmentation fault (core dumped)  node boom.js
    *** Error in `/usr/bin/nodejs': free(): invalid next size (fast): 0x0000000004a1d830 ***

**Comment by asmuth** [comment]
likely related to #6

**Comment by schroffl** [comment]
A little update on this issue:
Such a string (128 `x`'s) gets compressed so densely that the estimated size of the output-buffer for decompression (via `input.length * 3`) is way below the actual length. `lzo1x_decompress` doesn't check 
 whether the allocated memory is large enough to hold the decompressed data . This inevitably leads to a segfault.
