### ISSUE TITLE
Devtools was disconnected from the page. Lzo crashes.

### ISSUE THREAD

**Issue by NiketanMhatre** [schroffl/node-lzo#8]
Hello,
I am trying to decompress the binary data coming over LAN. Data is in LZO compression from server side. But LZO.decompress() failing to decompress it. and throwing error DevTools was disconnected. 

Can this library do binary operation for compression or decompression?

@schroffl I know you said not to use in critical operations, but I have no other option as data is in LZO compressed format so have to use this library.

![lzo](https://user-images.githubusercontent.com/7303269/32351737-7122ec32-c044-11e7-9a3c-e75d1b4a3f14.png)

**Comment by schroffl** [comment]
Binary data should work just fine. Anything that's not a buffer will be converted otherwise.
Citing my own documentation:

> If data is not a Buffer, the function will try to convert it via [Buffer.from](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding)

Do you mind giving me samples of your data so I can do some testing?

**Comment by NiketanMhatre** [comment]
Earlier I was using buffer but after checking documentation changed to variable
here is code snippet 
```
let message;
server.on("message", (message, remoteaddress) => {
  console.log(`${remoteaddress.address} : ${remoteaddress.port} -${message}`);
  console.log('Current version:', lzo.version, '-', lzo.versionDate);
  console.log(`message length ${message.length}`);  
  let decompressed = lzo.decompress(message, message.length);
});
```



[binary.zip](https://github.com/schroffl/node-lzo/files/1442198/binary.zip)

**Comment by NiketanMhatre** [comment]
I tested small piece I got this exact error may help in narrowing problem. I am testing with 512 bytes at a time.

I guess this problem is like #5 .. 

```
F:\electron\LZO-decompression\node_modules\lzo\index.js:60 Uncaught Error: Decompression failed with code: LZO_E_INPUT_OVERRUN
    at Object.decompress (F:\electron\LZO-decompression\node_modules\lzo\index.js:60:13)
    at fs.readFile (F:\electron\LZO-decompression\renderer.js:15:28)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

**Comment by schroffl** [comment]
Does it always show an error for you? I tried it yesterday and around half of the time node just crashes without any error message. 

**Edit**: I just tried it on MacOS and with that there's always a Segmentation Fault being reported, so it indeed seems to be the same problem as #5.
